artmedia: "https://media.betweenplanets.com/art/"
comicsmedia: "https://media.betweenplanets.com/comics/"
assets: "https://media.betweenplanets.com/assets/"

collections:
  art:
    output: true
  comics:
    output: true

defaults:
  - scope:
      path: ""
      type: "art"
    values:
      layout: "art"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed