url: https://www.betweenplanets.com
baseurl: dev/
permalink: /:title/

artmedia: "https://media.betweenplanets.com/art/"
comicsmedia: "https://media.betweenplanets.com/comics/"
assets: "https://media.betweenplanets.com/assets/"
animedia: "https://media.betweenplanets.com/animation/"

collections:
  animation:
    output: true
  art:
    output: true
  comics:
    output: true
  fullcomics:
    output: true
    permalink: /comics/:title/
  mobilecomics:
    output: true
    permalink: /comics/:title/

defaults:
  - scope:
      path: ""
      type: "comics"
    values:
      layout: "book_cover"
  - scope:
      path: ""
      type: "fullcomics"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "mobilecomics"
    values:
      layout: "book"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

exclude: ["/src media/","README.md","favicon*","/assets/images/","betweenplanets.code-workspace"]