permalink: /:title/
description: where stardust falls
title: '...between planets'

assets: "/assets/images/"
media: "/assets/media/images/"

linkopener: 'target="_blank" rel="noopener noreferrer"'

collections:
  animation:
    output: true
  art:
    output: true
  comics:
    output: true
  fullcomics:
    output: true
    permalink: /comics/:title/
  mobilecomics:
    output: true
    permalink: /comics/:title/
  music:
    output: true
  stories:
    output: true

defaults:
  - scope:
      path: ""
      type: "mobilecomics"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "fullcomics"
    values:
      layout: "comic_full"
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"
  - scope:
      path: ""
      type: "comics"
    values:
      layout: "story"
  - scope:
      path: ""
      type: "art"
    values:
      layout: "art_single"
  - scope:
      path: ""
      type: "animation"
    values:
      layout: "theater"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

exclude: ["/src media/","betweenplanets.code-workspace"]
