# url: https://www.betweenplanets.com/
# baseurl: dev/
permalink: /:title/

artmedia: "https://media.betweenplanets.com/art/"
comicsmedia: "https://media.betweenplanets.com/comics/"
assets: "https://media.betweenplanets.com/assets/"

collections:
  art:
    output: true
  comics:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

exclude: ["/src media/","README.md","favicon*","/assets/images/"]